version: "3.4"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - test-redis
  consumers:
    build:
      dockerfile: ./docker/consumers.Dockerfile
      context: ../
    volumes:
      - type: bind
        source: ../src
        target: /opt/src
    networks:
      - test-redis
  producers:
    build:
      dockerfile: ./docker/producers.Dockerfile
      context: ../
    volumes:
      - type: bind
        source: ../src
        target: /opt/src
    networks:
      - test-redis
networks:
  test-redis:
    driver: bridge